languageCode = "en"
languageName = "English"
weight = 1
title = "Anna Kleiman"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Practical Scandologist: Provokes scandals, then writes about them."

[params.author]
  name = "Anna Kleiman"
  email = "annakleiman@gmail.com"
  headline = "Scanadlogist scholar"
  bio = "Helm me lord omfg"
  links = [
    { bluesky = "https://bsky.app/profile/yourhandle.bsky.social" },
    { github = "https://github.com/yourusername" },
    { email = "mailto:r.huffington-smythe@university.edu" },
  ]
  image = "img/Rooster.png"